version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:8.6
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      # ðŸ‘‡æŠŠå†…éƒ¨ç›®å½•æ˜ å°„åˆ°ä¸€ä¸ªå‘½åå·
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

  airflow-init:
    image: apache/airflow:2.9.2-python3.11
    restart: "no"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - HTTP_PROXY=http://host.docker.internal:1082
      - HTTPS_PROXY=http://host.docker.internal:1082
      - http_proxy=http://host.docker.internal:1082
      - https_proxy=http://host.docker.internal:1082
      - "_PIP_ADDITIONAL_REQUIREMENTS=openai psycopg2-binary python-dotenv requests~=2.31.0 scikit-learn>=1.4.0 pandas>=1.5.0 numpy>=1.21.0 ruamel.yaml>=0.18.0 sqlalchemy>=1.4.0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scraper:/opt/airflow/scraper
      - ./utils:/opt/airflow/utils
      - ./logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    command:
      - bash
      - -c
      - |
        airflow db migrate
        
        airflow users create \
          --username "${AIRFLOW_ADMIN_USER}" \
          --firstname "Admin" \
          --lastname "User" \
          --role "Admin" \
          --email "${AIRFLOW_ADMIN_EMAIL}" \
          --password "${AIRFLOW_ADMIN_PASSWORD}"
    networks:
      - backend

  airflow-webserver:
    image: apache/airflow:2.9.2-python3.11
    restart: unless-stopped
    depends_on:
      - airflow-init
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - HTTP_PROXY=http://host.docker.internal:1082
      - HTTPS_PROXY=http://host.docker.internal:1082
      - http_proxy=http://host.docker.internal:1082
      - https_proxy=http://host.docker.internal:1082
      - TW_BEARER_TOKEN=${TW_BEARER_TOKEN}
      - TWITTER_USERS=${TWITTER_USERS}
      - "_PIP_ADDITIONAL_REQUIREMENTS=openai psycopg2-binary python-dotenv requests~=2.31.0 scikit-learn>=1.4.0 pandas>=1.5.0 numpy>=1.21.0 ruamel.yaml>=0.18.0 sqlalchemy>=1.4.0"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scraper:/opt/airflow/scraper
      - ./utils:/opt/airflow/utils
      - ./exports:/opt/airflow/exports
      - ./logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    command: webserver

    networks:
      - backend

  airflow-scheduler:
    image: apache/airflow:2.9.2-python3.11
    restart: unless-stopped
    depends_on:
      - airflow-init
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - HTTP_PROXY=http://host.docker.internal:1082
      - HTTPS_PROXY=http://host.docker.internal:1082
      - http_proxy=http://host.docker.internal:1082
      - https_proxy=http://host.docker.internal:1082
      - TW_BEARER_TOKEN=${TW_BEARER_TOKEN}
      - TWITTER_USERS=${TWITTER_USERS}
      - "_PIP_ADDITIONAL_REQUIREMENTS=openai psycopg2-binary python-dotenv requests~=2.31.0 scikit-learn>=1.4.0 pandas>=1.5.0 numpy>=1.21.0 ruamel.yaml>=0.18.0 sqlalchemy>=1.4.0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scraper:/opt/airflow/scraper
      - ./utils:/opt/airflow/utils
      - ./exports:/opt/airflow/exports
      - ./logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - backend
volumes:
  postgres_data:
  airflow_plugins:
  pgadmin-data:

networks:
  backend:
    driver: bridge


